name: infra

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "**/template.yml"
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/staging' && 'staging'}}

    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: SAM Build
        run: sam build

      - name: SAM Deploy
        run: sam deploy --stack-name ${{ vars.STACK_NAME }} --parameter-overrides StackName='${{ vars.STACK_NAME }}' DomainName='${{vars.UI_DOMAIN}}' HostedZoneId='${{VARS.AWS_HOSTED_ZONE_ID}}' CertificateId='${{VARS.AWS_CERTIFICATE_ID}}'
